services:
  api:
    container_name: api
    # image: test-api-manual-build
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    command: bun dev api
    restart: always
    depends_on:
      - postgres
      - swap
    env_file:
      - ./apps/api/.env
    ports:
      - '4000:4000'
    volumes:
      - .:/usr/src/app
  swap:
    container_name: swap
    # image: test-swap-manual-build
    build:
      context: .
      dockerfile: ./apps/swap/Dockerfile
      target: development
    command: [
        "sh",
        "-c",
        "bun prisma migrate deploy --schema apps/swap/prisma/schema.prisma && bun dev swap"
      ]
    restart: always
    depends_on:
      - swap-clientd
      - postgres
      - redis
    env_file:
      - ./apps/swap/.env
    ports:
      - '4040:4040'
    volumes:
      - .:/usr/src/app
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=bs
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_datadir:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
  swap-clientd:
    image: okjodom/fedimint-clientd:v0.4.0
    container_name: swap-clientd
    environment:
      - FEDIMINT_CLIENTD_DB_PATH=/var/lib/clientd
      - FEDIMINT_CLIENTD_PASSWORD=fmcdpass
      - FEDIMINT_CLIENTD_ADDR=0.0.0.0:7070
      - FEDIMINT_CLIENTD_MODE=rest
      - FEDIMINT_CLIENTD_INVITE_CODE=fed11qgqrwdthwden5te0v9cxjttndakk2ttrdpjk2um994erx7rsx568vur9dy68z6pnvd6xg63hwsh8wmn90p6zuctswqhsqqfqt94ttf29vdm0jfw3gk3w7quvcknshxd705ksavc0ajj7sj0v6dgsxcydnc
    ports:
      - 0.0.0.0:7070:7070
    volumes:
      - swap_clientd_datadir:/var/lib/clientd
    restart: always
volumes:
  postgres_datadir:
  swap_clientd_datadir:
